#!/bin/bash

go install bitbucket.org/camilobermudez/huitaca/drivers
go install bitbucket.org/camilobermudez/huitaca/utils
go install bitbucket.org/camilobermudez/huitaca
go install bitbucket.org/camilobermudez/huitaca/cmd
