#!/bin/bash

DOCKER_REPO="huitaca"
IMAGE_NAME="tomcat-dev"

build_images() {
    tag=$1
    if [ ! -z ${tag} ] && [ -d ${tag} ]; then
        docker build -t "${DOCKER_REPO}/${IMAGE_NAME}:${tag}" "${tag}"
    else
        for tag in $(find . -type d -regex "./[0-9]+.?[0-9]?-java[1-9]" -printf '%P\n' -prune); do
            docker build -t "${DOCKER_REPO}/${IMAGE_NAME}:${tag}" "${tag}"
        done
    fi
}

build_images "$@"
