#!/bin/bash

test_image() {
    tag=$1
    if [ ! -z ${tag} ] && [ -d ${tag} ]; then
        full_name="${DOCKER_REPO}/${IMAGE}-candidate:${tag}"
        docker build -t "${full_name}" "${tag}"
        IMAGE_NAME=${full_name} ./.test/run
    else
        for tag in $(find . -type d -regex "./[0-9]+.?[0-9]?-java[1-9]" -printf '%P\n' -prune); do
            full_name="${DOCKER_REPO}/${IMAGE}-candidate:${tag}"
            docker build -t "${full_name}" "${tag}"
            IMAGE_NAME=${full_name} ./.test/run
        done
    fi
}

test_image "$@"
